### PR TITLE
Add support for custom html editors

### PR DESCRIPTION
**Pull request by ryanlntn**
Adds support for a user defined custom html editor. 

screen shot 2017-05-24 at 11 23 54 pm

Editors must implement the following interface:
```
constructor/1
enable/0
disable/0
content/1
set/2
```

Example from the above screenshot:
```js
import $ from 'jquery'
import './vendor/trumbowyg.min'

class CustomEditor {
  constructor (opts) {
    this.editors = document.querySelectorAll('.thesis-content-html')
    this.enabled = false
    this.onChange = opts.onChange
    this.changedHtmlEditor = this.changedHtmlEditor.bind(this)
  }

  enable () {
    if (this.enabled) return
    if (this.editors.length > 0) {
      $(this.editors).trumbowyg({
        btns: [
          ['viewHTML'],
          'btnGrp-design',
          ['formatting'],
          ['link'],
          ['justifyLeft', 'justifyCenter', 'justifyRight'],
          'btnGrp-lists',
          ['removeformat'],
          ['fullscreen']
        ]
      })
      $('.trumbowyg-box').css('z-index', 9999)
      $(this.editors).on('tbwchange', this.changedHtmlEditor)
    }
    this.enabled = true
  }

  disable () {
    if (!this.enabled) return
    $(this.editors).trumbowyg('destroy')
    this.enabled = false
  }

  content (ed) {
    return ed.innerHTML
  }

  set (name, data) {
    const ed = document.querySelector(`[data-thesis-content-id='${name}']`)
    if (!ed) return
    ed.innerHTML = data.content
    ed.classList.add('modified')
  }

  changedHtmlEditor (event) {
    event.target.classList.add('modified')
    this.onChange()
  }
}

window.CustomEditor = CustomEditor

export default CustomEditor
```

### CODE REVIEW

**Comment by jamonholmgren** [comment]
Surprisingly little code. LGTM.

**Comment by jamonholmgren** [comment]
Can you add documentation?

**Comment by jamonholmgren** [comment]
Hm, `./doc` won't work because that's auto-generated. At least in the README for now, or create a new document for this.

**Comment by ryanlntn** [comment]
@jamonholmgren Heads up that I added docs to the readme.

**Pull request merged**
