### PR TITLE
Add ecto, html_sanitize_ex and lz_string to applications list

### PR DESCRIPTION
**Pull request by Gazler**
If these are not present then thesis will not work in a release.

### CODE REVIEW

**Comment by Gazler** [comment]
This isn't compatible with https://github.com/infinitered/thesis-phoenix/pull/123 - I'd recommend using the other PR since using application inference will prevent this sort of issue in the future.

**Comment by jamonholmgren** [comment]
@Gazler Thanks! Is there any benefit to this over #123? I'll go with #123 since you recommend it.

BTW, good talk at ElixirConf! Really enjoyed it.

**Comment by Gazler** [comment]
@jamonholmgren Thanks!

So, prior to Elixir 1.4, you had to specify all the applications in the applications list (as in this PR). I wasn't sure if you were sticking with the 1.3 format for any particular reason, or if you just hadn't updated the mix.exs file yet. I figured it'd take less time to open both PRs than to check first!

**Comment by jamonholmgren** [comment]
I'm fine with only supporting 1.4 going forward -- in fact, I believe we have other reasons for doing that, so I'm cool with the 1.4 format!

**Pull request closed without merging**
